experiment_id: "2025-01-02_B2_lucchi+droso_dinov2-base_lora-none_pca-umap"
results_root: "/Users/cfuste/Documents/Results/DINO-LoRA"
task_type: "feats"

data:
  input_path: "/Users/cfuste/Documents/Results/DINO-LoRA/feats/2025-12-02_A5_lucchi+droso_dinov2-base_lora-none_feats/features.npz"

pca:
  n_components: 50  # pre-UMAP PCA
  plot_dims: [0, 1] # for PCA plots if desired
  whiten: false
  l2norm: false
  seed: 0

umap:
  enabled: true
  n_neighbors: 15
  min_dist: 0.1
  n_components: 2
  metric: euclidean  # or cosine
  seed: 0
  output_path: ...  # optional override; else derive from input
