name: dino-peft
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libcblas=3.11.0=2_h0358290_openblas
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=2_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libuuid=2.41.1=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h031cc0b_0
  - libxml2-16=2.15.1=hf2a90c1_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.45.1=py310hee1c697_0
  - narwhals=2.12.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - numba=0.62.1=py310h3477d8a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyh8b19718_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - python=3.10.18=hd6af730_0_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.7.2=py310h228f341_0
  - setuptools=80.9.0=pyhff2d567_0
  - tbb=2022.3.0=h8d10470_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=pyhd8ed1ab_1
  - umap-learn=0.5.9.post2=py310hff52083_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - alembic==1.16.5
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.3.0
      - authlib==1.6.4
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cryptography==45.0.7
      - cycler==0.12.1
      - cyclopts==3.24.0
      - databricks-sdk==0.67.0
      - dino-peft==0.0.1
      - dinov2==0.0.1
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.118.0
      - fastmcp==2.12.4
      - filelock==3.13.1
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jsonschema==4.25.1
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-object-proxy==1.12.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - mcp==1.15.0
      - mdurl==0.1.2
      - monai==1.5.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opentelemetry-api==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - pandas==2.3.3
      - parse==1.20.2
      - pathable==0.4.4
      - pillow==11.0.0
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytorch-fid==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rich==14.1.0
      - rich-rst==1.3.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scipy==1.15.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - sympy==1.13.1
      - tomli==2.2.1
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - triton==3.1.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - werkzeug==3.1.1
      - zipp==3.23.0
