name: dino-peft
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.8=h8869778_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=h19e8193_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - alembic==1.16.5
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.3.0
      - authlib==1.6.5
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - contourpy==1.3.3
      - cryptography==45.0.7
      - cycler==0.12.1
      - cyclopts==3.24.0
      - databricks-sdk==0.67.0
      - dino-peft==0.0.1
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.118.0
      - fastmcp==2.12.4
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - idna==3.10
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-object-proxy==1.12.0
      - llvmlite==0.45.1
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mcp==1.16.0
      - mdurl==0.1.2
      - monai==1.5.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - narwhals==2.13.0
      - networkx==3.5
      - numba==0.62.1
      - numpy==2.3.3
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opentelemetry-api==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - pandas==2.3.3
      - parse==1.20.2
      - pathable==0.4.4
      - pillow==11.3.0
      - plotly==6.5.0
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytorch-fid==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rich==14.1.0
      - rich-rst==1.3.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap==0.1.1
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - werkzeug==3.1.1
